name: Exploring Variables and Secrets

on: 
  push

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       run: docker build -t docker.io/dockerUsername/imageName:latest

#     - name: Docker Login
#       run: docker login --usename=dockerUsername --password=s3curePaSsw0rd

#     - name: Docker Publish
#       run: docker push docker.io/dockerUsername/imageName:latest

#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

# ######################## environment variables at STEP level ####################################

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build
#       env: 
#         CONTAINER_REGISTRY: docker.io
#         {{ vars.DOCKER_USERNAME }}: reivson
#         IMAGE_NAME: github-actions-nginx
#       run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

#     - name: Docker Login
#       env:
#         {{ vars.DOCKER_USERNAME }}: reivson
#         DOCKER_PASSWORD: s3curePaSsw0rd
#       run: docker login --usename=${{ vars.DOCKER_USERNAME }} --pasword=$DOCKER_PASSWORD

#     - name: Docker Publish
#       env: 
#         CONTAINER_REGISTRY: docker.io
#         {{ vars.DOCKER_USERNAME }}: reivson
#         IMAGE_NAME: github-actions-nginx
#       run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

#   deploy:
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       env: 
#         CONTAINER_REGISTRY: docker.io
#         {{ vars.DOCKER_USERNAME }}: reivson
#         IMAGE_NAME: github-actions-nginx
#       run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

######################## environment variables at JOB level ####################################

# jobs:
#   docker:
#     env: 
#       CONTAINER_REGISTRY: docker.io
#       {{ vars.DOCKER_USERNAME }}: reivson
#       IMAGE_NAME: github-actions-nginx
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Build 
#       run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

#     - name: Docker Login
#       env: 
#         DOCKER_PASSWORD: s3curePaSsw0rd
#       run: docker login --usename=${{ vars.DOCKER_USERNAME }} --pasword=$DOCKER_PASSWORD

#     - name: Docker Publish
#       run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

#   deploy:
#     env: 
#       CONTAINER_REGISTRY: docker.io
#       {{ vars.DOCKER_USERNAME }}: reivson
#       IMAGE_NAME: github-actions-nginx
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

######################## environment variables at WORKFLOW level ####################################

env: 
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build 
      run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

    - name: Docker Login
      run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest